#ifndef CONFIG_H
#define CONFIG_H

#define PROTOCOL_VERSION 0x01

#define CYCLE_TIME 100

//#define CREMOTE_CMD_TRANSMITTER_DEBUG_OUTPUT
//#define CTCPSOCKET_DEBUG_OUTPUT
//#define CCMDSHELL_DEBUG_OUTPUT

#endif
